# SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
#
# SPDX-License-Identifier: Apache-2.0

version: 2

multi-ecosystem-groups:
  docker:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      opentelemetry:
        patterns: ["opentelemetry-*"]

  - package-ecosystem: pip
    directory: /cli
    schedule:
      interval: weekly
    labels: [dependencies]
  
  - package-ecosystem: docker
    directory: /api
    multi-ecosystem-group: docker
    labels: [dependencies]

  - package-ecosystem: docker
    directory: /viewer
    multi-ecosystem-group: docker
    labels: [dependencies]
