#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
# SPDX-License-Identifier: Apache-2.0
#

if [ -z "$PORT" ]; then
  PORT=6453
fi
if [ -z "$TIMEOUT" ]; then
  TIMEOUT=30
fi
export PORT TIMEOUT

# Set locale
export LANG='C.utf8'
export LC_ALL='C.utf8'

# Directory for gunicorn and prometheus
export XDG_RUNTIME_DIR="/app/run"
mkdir -p "${XDG_RUNTIME_DIR}"
chown app:app "${XDG_RUNTIME_DIR}"
export HOME="${XDG_RUNTIME_DIR}"

set -e

gunicorn -k gthread --bind "[::]:${PORT}" --timeout ${TIMEOUT} $@ 'dnsprobe:create_http_app()'
