#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
# SPDX-License-Identifier: Apache-2.0
#

if [ -z "$LISTEN_ADDR" ]; then
  LISTEN_ADDR='[::]'
fi
if [ -z "$PORT" ]; then
  PORT=6453
fi
if [ -z "$TIMEOUT" ]; then
  TIMEOUT=30
fi
export LISTEN_ADDR PORT TIMEOUT

# Set locale
export LANG='C.utf8'
export LC_ALL='C.utf8'

set -e

echo "Starting DNSProbe via gunicorn on ${LISTEN_ADDR}:${PORT} with timeout ${TIMEOUT}...\n" >&2
gunicorn --bind "${LISTEN_ADDR}:${PORT}" --timeout ${TIMEOUT} $@ 'dnsprobe:create_http_app()'