#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
# SPDX-License-Identifier: Apache-2.0
#

if [ -z "$PORT" ]; then
  PORT=6453
fi
if [ -z "$TIMEOUT" ]; then
  TIMEOUT=30
fi
export PORT TIMEOUT

# Set locale
export LANG='C.utf8'
export LC_ALL='C.utf8'

printenv

set -e

gunicorn --bind "[::]:${PORT}" --timeout ${TIMEOUT} $@ 'dnsprobe:create_http_app()'