{{- if .Values.prometheus.enabled  -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ include "webres6.fullname" . }}
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
    {{- if .Values.prometheus.additionalLabels }}
    {{- with .Values.prometheus.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: webres6-api
      {{- include "webres6.selectorLabels" . | nindent 4 }}
      {{- with .Values.api.podLabels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  podMetricsEndpoints:
  - port: {{ .Values.api.port | quote }}
    path: /metrics
    basicAuth:
      password:
        name: {{ .Values.adminSecret.name | default (include "webres6.fullname" .) }}
        key: admin-key
{{- end }}