{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ include "webres6.fullname" . }}
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /res6
            pathType: Prefix
            backend:
              service:
                name: {{ include "webres6.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- with $.Values.ingress.additionalPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "webres6.fullname" $ }}-viewer
                port:
                  number: {{ $.Values.viewer.service.port }}
    {{- end }}
{{- end }}
