apiVersion: v1
kind: ConfigMap
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ include "webres6.fullname" . }}-viewer-well-known
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
data:
  {{- if .Values.well_known }}
  {{- with .Values.well_known }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- else }}
  # If no well-known configuration is provided
  {{- end }}