{{- if .Values.adminSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ .Values.adminSecret.name | default (include "webres6.fullname" .) }}
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
  {{- with .Values.adminSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- /* Generate random string of specified length if not provided */}}
  admin-key: {{ randAlphaNum (.Values.adminSecret.keyLength | int) | b64enc | quote }}
{{- end }}