#!/bin/bash
#
# SPDX-FileCopyrightText: 2026 SAP SE and IPv6 Web Resource Checker contributors
# SPDX-License-Identifier: Apache-2.0
#

DIR=$(cd $(dirname $(readlink -f "$0")) && pwd)

cd "$DIR"
exec uv run webres6-mcp