#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
# SPDX-License-Identifier: Apache-2.0
#

if [ -z "$LISTEN_ADDR" ]; then
  LISTEN_ADDR='[::]'
fi
if [ -z "$PORT" ]; then
  PORT=6400
fi
if [ -z "$TIMEOUT" ]; then
  TIMEOUT=180
fi
export LISTEN_ADDR PORT TIMEOUT

# Set locale
export LANG='C.utf8'
export LC_ALL='C.utf8'
export TZ='UTC'

# Fix python buffering
export PYTHONUNBUFFERED=1

# Directory for gunicorn and prometheus
export XDG_RUNTIME_DIR="/app/run"
mkdir -p "${XDG_RUNTIME_DIR}"
export PROMETHEUS_MULTIPROC_DIR="/app/run/prometheus-mp"
mkdir -p "${PROMETHEUS_MULTIPROC_DIR}"

set -e

if [ -z "$1" ]; then
  echo "Starting webres6-api via gunicorn on ${LISTEN_ADDR}:${PORT} with timeout ${TIMEOUT}..." >&2
  gunicorn -k gthread --bind "${LISTEN_ADDR}:${PORT}" --timeout ${TIMEOUT} $@ 'webres6_api:create_http_app()'
else
  echo "Starting webres6-api with custom arguments: $@" >&2
  ./webres6_api.py $@
fi
